[profs.dev]
    [[profs.dev.links]]
    src = "vim/.vimrc"
    dst = ".vimrc"

    [[profs.dev.links]]
    src = "vim/.vim"
    dst = ".vim"

    [[profs.dev.links]]
    src = ".gitconfig"

[profs.base]
    [[profs.base.links]]
    src = ".config/fish"

    [[profs.base.links]]
    src = ".config/keepassx"

    [[profs.base.links]]
    src = ".filezilla"

    [[profs.base.links]]
    src = "profsile"

[profs.study]
    [[profs.study.links]]
    src = "Anki"

    [[profs.study.links]]
    src = ".yomichan.json"

[profs.net]
    [[profs.net.links]]
    src = ".filezilla"

    [[profs.net.links]]
    src = ".s3cfg"

[profs.flatline]
    deps = ["base", "dev", "study", "net"]

    [[profs.flatline.links]]
    src = ".ssh_flatline"
    dst = ".ssh"

    [[profs.flatline.links]]
    src = ".config/syncthing_flatline"
    dst = ".config/syncthing"

[profs.wintermute]
    deps = ["base", "dev", "study"]

    [[profs.wintermute.links]]
    src = ".ssh_wintermute"
    dst = ".ssh"
