[tasks.dev]
    [[tasks.dev.links]]
    src = ".gitconfig"

[tasks.base]
    [[tasks.base.links]]
    src = ".config/fish"

    [[tasks.base.links]]
    src = ".config/keepassx"

    [[tasks.base.links]]
    src = ".filezilla"

    [[tasks.base.links]]
    src = "profile"

[tasks.study]
    [[tasks.study.links]]
    src = "Anki"

    [[tasks.study.links]]
    src = ".yomichan.json"

[tasks.net]
    [[tasks.net.links]]
    src = ".filezilla"

    [[tasks.net.links]]
    src = ".s3cfg"

[tasks.flatline]
    deps = ["base", "dev", "study", "net"]

    [[tasks.flatline.links]]
    src = ".ssh_flatline"
    dst = ".ssh"

    [[tasks.flatline.links]]
    src = ".config/syncthing_flatline"
    dst = ".config/syncthing"

[tasks.wintermute]
    deps = ["base", "dev", "study"]

    [[tasks.wintermute.links]]
    src = ".ssh_wintermute"
    dst = ".ssh"
